myproject/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.BooksModelView.as_view(), name='index'),
    path('book/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),

    path('book/<int:pk>', views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>', views.PublisherDetail.as_view(), name='publisher_detail'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

from myproject import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('polls/', include('polls.urls')),
    path('books/', include('books.urls')),
    path('', views.HomeView.as_view(), name='Home')
]

myproject/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("<int:pk>/", views.DetailView.as_view(), name='detail'),
    path("<int:question_id>/vote/", views.vote, name='vote'),
    path("<int:pk>/results/", views.ResultView.as_view(), name='results'),
]

myproject/books/models.py
from django.db import models


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_date = models.DateField()

    def __str__(self):
        return self.title


class Author(models.Model):
    name = models.CharField(max_length=50)
    salutation = models.CharField(max_length=100)
    email = models.EmailField()

    def __str__(self):
        return self.name


class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)
    website = models.URLField()

    def __str__(self):
        return self.name

myproject/polls/models.py
from django.db import models


# Create your models here.
class Question(models.Model): #문제
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model): #다항식
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0) #사용자 수

    def __str__(self):
        return self.choice_text

myproject/books/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView

from books.models import Book, Author, Publisher


# Create your views here.
class BooksModelView(TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context


class BookList(ListView):
    model = Book


class AuthorList(ListView):
    model = Author


class PublisherList(ListView):
    model = Publisher


class BookDetail(DetailView):
    model = Book


class AuthorDetail(DetailView):
    model = Author


class PublisherDetail(DetailView):
    model = Publisher

myproject/myproject/views.py
import logging

from django.views.generic import TemplateView

from django.apps import apps

class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['app_list'] = ['polls', 'books']
        dictVerbose = {}
        for app in apps.get_app_configs():
            logging.getLogger('TEST').fatal(app.path)
            if 'site-packages' not in app.path:
                dictVerbose[app.label] = app.verbose_name
        context['verbose_dict'] = dictVerbose
        return context

myproject/polls/views.py
import logging

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic

from polls.models import Question, Choice

logger = logging.getLogger(__name__)


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        # 최근 생성된 질문 5개를 반환함
        return Question.objects.all().order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    logger.fatal('vote')
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

myproject/books/templates/books/author_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <ul>
        <li>{{ object.salutation }}</li>
        <li>Email: {{ object.email }}</li>
    </ul>
{% endblock content %}

myproject/books/templates/books/author_list.html
{% extends "base.html" %}

{% block content %}
<h2>Author List</h2>
<ul>
    {% for author in object_list %}
    <li>
        <a href="{% url 'books:author_detail' author.id %}">
            {{ author.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

myproject/books/templates/books/book_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ object.title }}</h1>
    <ul>
        <li>
            Authors:
            {% for author in object.authors.all %}
                {{ author }}
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </li>
        <li>
            Publisher: {{ object.publisher }}
        </li>
        <li>
            Publication date: {{ object.publication_date }}
        </li>
    </ul>
{% endblock content %}

myproject/books/templates/books/book_list.html
{% extends "base.html" %}

{% block content %}
<h2>Book List</h2>
<ul>
    {% for book in object_list %}
        <li>
            <a href="{% url 'books:book_detail' book.id %}">
                {{ book.title }}
            </a>
        </li>
    {% endfor %}
</ul>
{% endblock %}

myproject/books/templates/books/index.html
{% extends "base_books.html" %}

{% block content %}
<h1>Book Management System</h1>
<ul>
    {% for modelname in model_list %}
        {% with "books:"|add:modelname|lower|add:"_list" as url_var %}
        <!--    books:book_list books:author_list books:publisher -->
        <li><a href="{% url url_var %}">{{ modelname }}</a></li>
        {% endwith %}
    {% endfor %}
</ul>
{% endblock %}

myproject/books/templates/books/publisher_detail.html
{% extends 'base_books.html' %}

{% block content %}
    <h1>{{ object.name }}</h1>
    <ul>
        <li>{{ object.website }}</li>
        <li>Address: {{ object.address }}</li>
    </ul>
{% endblock content %}

myproject/books/templates/books/publisher_list.html
{% extends "base_books.html" %}

{% block content %}
<h2>Publisher List</h2>
<ul>
    {% for publisher in object_list %}
    <li>
        <a href="{% url 'books:publisher_detail' publisher.id %}">
            {{ publisher.name }}
        </a>
    </li>
    {% endfor %}
</ul>
{% endblock %}

myproject/polls/templates/polls/detail.html
{% extends "base_polls.html" %}

{% block content %}
    <form action="{% url 'polls:vote' question.id %}" method="post">
        {% csrf_token %}
        <fieldset>
            <legend>
                <h1>{{ question.question_text }}</h1>
            </legend>
            {% if error_message %}
                <p><strong>{{ error_message }}</strong></p>
            {% endif %}
            {% for choice in question.choice_set.all %}
                <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
                <br>
            {% endfor %}
        </fieldset>
        <input type="submit" value="Vote">
    </form>
{% endblock content %}

myproject/polls/templates/polls/index.html
{% extends "base_polls.html" %}

{% block title %}My Title{% endblock %}

{% block content %}
<!--views.py > index > context > latest_question_list -->
{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li>
        <a href="/polls/{{question.id}}">{{ question.question_text|default:'질문이 없습니다.' }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>투표가 없습니다.</p>
{% endif %}
{% endblock %}

myproject/polls/templates/polls/results.html
{% extends 'base_polls.html' %}

{% block content %}
    <h1>{{ question.question_text }}</h1>

    <ul>
        {% for choice in question.choice_set.all %}
            <li>
                {{ choice.choice_text }} - {{ choice.votes }} vote{{ choice.votes|pluralize }}
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock content %}

myproject/templates/base.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        {% block title %}My Site{% endblock %}
    </title>
</head>
<body style="display: flex; flex-direction: row; align-items: center">

<div id="sidebar" style="margin-left : 3rem ">
    {% block sidebar %}
        <ul>
            <li><a href="/">Project_Home</a></li>
            <li><a href="/admin">Admin</a></li>
        </ul>
    {% endblock sidebar %}
</div>

<div id="content" style="margin-left : 3rem">
    {% block content %}{% endblock %}
</div>

</body>
</html>

myproject/templates/base_books.html
{% extends 'base.html' %}

<title>{% block title %}Books Application Site{% endblock title %}</title>

{% block sidebar %}
    {{ block.super }}
    <ul>
        <li><a href="/books/">Books Home</a></li>
    </ul>
{% endblock sidebar %}

myproject/templates/base_polls.html
{% extends 'base.html' %}

{% block title %}Polls Application Site{% endblock title %}

{% block sidebar %}
    {{ block.super }}
    <ul>
        <li><a href="/polls/">Polls Home</a></li>
    </ul>
{% endblock sidebar %}

myproject/templates/home.html
{% extends 'base.html' %}

{% block content %}
    <h1>Django Applications</h1>
    <ul>
        {% for key, value in verbose_dict.items %}
            <li><a href="{% url key|add:':index' %}">{{ value }}</a></li>
        {% endfor %}
    </ul>
{% endblock content %}